In [12]:
import bq_helper
from bq_helper import BigQueryHelper
# https://www.kaggle.com/sohier/introduction-to-the-bq-helper-package
noaa = bq_helper.BigQueryHelper(active_project="bigquery-public-data",
                                   dataset_name="ghcn_d")

In [13]:
query = (
    """SELECT
  id,
  name,
  state,
  latitude,
  longitude
FROM
  `bigquery-public-data.ghcn_d.ghcnd_stations`
WHERE
  latitude > 41.7
  AND latitude < 42
  AND longitude > -87.7
  AND longitude < -87.5;"""
)

In [17]:
query_new = (
    """SELECT * 
    FROM
    `bigquery-public-data.ghcn_d.ghcnd_2018`;
""")

In [19]:
response1 = noaa.query_to_pandas_safe(query_new, max_gb_scanned=2)

KeyboardInterrupt:

In [1]:
from google.cloud import bigquery
client = bigquery.Client()

In [2]:
query1 = """SELECT
  id,
  name,
  state,
  latitude,
  longitude
FROM
  `bigquery-public-data.ghcn_d.ghcnd_stations`
WHERE
  latitude > 41.7
  AND latitude < 42
  AND longitude > -87.7
  AND longitude < -87.5;
        """

In [3]:
query_job = client.query(
    query1,
    # Location must match that of the dataset(s) referenced in the query.
    location="US",
)

In [7]:
response1

             id                            name state  latitude  longitude
0   USC00111562  CHICAGO SAN DIST OFC              IL   41.9000   -87.6333
1   US1ILCK0117  CHICAGO 3.0 NW                    IL   41.9125   -87.6695
2   US1ILCK0108  BEVERLY 0.3 N                     IL   41.7165   -87.6710
3   US1ILCK0104  LINCOLNWOOD 5.1 SE                IL   41.9494   -87.6703
4   US1ILCK0151  EVERGREEN PARK 0.5 NE             IL   41.7274   -87.6949
5   US1ILCK0122  CHICAGO 6.5 NNE                   IL   41.9272   -87.6517
6   USC00111557  CHICAGO RACINE PUMP               IL   41.8167   -87.6500
7   US1ILCK0097  CHICAGO 6.8 NNE                   IL   41.9301   -87.6393
8   USC00111584  CHICAGO WB CITY 2                 IL   41.8833   -87.6333
9   US1ILCK0010  CHICAGO 3.0 N                     IL   41.8798   -87.6823
10  USW00014892  CHICAGO UNIV                      IL   41.7833   -87.6000
11  USC00111532  CHICAGO LAKEVIEW PUMP             IL   41.9667   -87.6667
12  US1ILCK0204  BOOT CAMP-CHICAGO 4.2 SW          IL   41.8421   -87.6891
13  US1ILCK0036  CHICAGO 4.7 NE                    IL   41.8860   -87.6210
14  USC00111550  CHICAGO NORTHERLY IS              IL   41.8558   -87.6094
15  US1ILCK0168  RAVENSWOOD MANOR 0.1 ESE          IL   41.9642   -87.6974
16  US1ILCK0032  CHICAGO 6.4 NNE                   IL   41.9266   -87.6562
17  USC00111564  CHICAGO S WTR FILT PLT            IL   41.7500   -87.5500
18  US1ILCK0214  ROGERS PARK 1.5 SW                IL   41.9957   -87.6918
19  US1ILCK0055  CHICAGO 6.0 NNE                   IL   41.9170   -87.6386
20  US1ILCK0014  CHICAGO 5.5 ESE                   IL   41.8008   -87.5903
21  US1ILCK0179  CHICAGO 4.8 NNW                   IL   41.9481   -87.6588
22  US1ILCK0240  CHICAGO 2.7 WNW                   IL   41.9018   -87.6726
23  USC00111526  CHICAGO GRANT PARK                IL   41.8833   -87.6167
24  USW00014881  FORT DEARBORN                     IL   41.8883   -87.6258

In [ ]:
response1.shape

In [ ]:
bq_assistant = BigQueryHelper("bigquery-public-data","ghcnd_2018")
bq_assistant.estimate_query_size(query_new)